name: Test api 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: install fastapi
        run: pip install fastapi
      - name: install b
        run: pip install pytest
      - name: install c
        run: pip install faker
      - name: install d
        run: pip install requests
      - name: install e
        run: pip install sqlalchemy
      - name: install f
        run: pip install httpx
      - name: install g
        run: pip install "pydantic[email]<2.0"
      - name: install h
        run: pip install python-jose
      - name: install i
        run: pip install passlib[bcrypt]
      - name: run tests
        run: pytest -vv
      
      
